[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "openzeppelin-contracts-08/=lib/openzeppelin-contracts-08/contracts/",
  "openzeppelin-contracts-06/=lib/openzeppelin-contracts-06/contracts/",
  "openzeppelin-contracts-v5.4.0/=lib/openzeppelin-contracts-v5.4.0/contracts/",
  "openzeppelin-contracts-v4.6.0/=lib/openzeppelin-contracts-v4.6.0/contracts"
]
[lint]
exclude_lints = [
  "unwrapped-modifier-logic",
  "mixed-case-variable",
  "screaming-snake-case-immutable",
  "unaliased-plain-import",
  "unused-import",
  "screaming-snake-case-const",
  "unchecked-call",
  "erc20-unchecked-transfer",
  "mixed-case-function",
  "asm-keccak256",
  "unsafe-typecast",
  "pascal-case-struct"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options